---
- name: Python და PIP3 ინსტალაცია
  hosts: all
  become: true

  tasks:
  - name: APT ქეშის განახლება
    apt: update_cache=yes cache_valid_time=3600

  - name: Python და PIP3-ის დაყენება
    apt:
      name:
        - python3
        - python3-pip
      state: present
  
  - name: Python-ის სტატუსი 
    shell: python -v

  - name: PIP-ის სტატუსი 
    shell: pip3 --version
